### ISSUE TITLE
Setup contributor guidelines, code of conduct, etc

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#1]

**Comment by digitalWestie** [comment]
Added and modified from the toolbox templates. Under the [Code of conduct](https://github.com/openactive/api-dashboard/blob/master/.github/CODE_OF_CONDUCT.md#enforcement 
) there's a contact email, is this still the same?

**Comment by digitalWestie** [comment]
Make sure to refer to OpenActive apart from license. 
hello [at] openactive.io for email.
