### ISSUE TITLE
Build activity counts in redis sets

### ISSUE THREAD

**Issue by digitalWestie** [openactive/api-dashboard#24]
Activity Counter

Feed object is constructed with the data-url or final-page-url (if available from previous harvesting)

Harvester pages until first results in 2017 then
For X number of opportunities (or end of feed)
Loop through all of opportunities adding the activity names into a redis sorted set (zincrby)

When finished store the final page url for harvesting later

**Comment by ldodds** [comment]
Only process datasets that conform to both specifications.

**Comment by digitalWestie** [comment]
Ignore items with a deleted state property

**Comment by digitalWestie** [comment]
Re-opened as I'll need to support various formats for  "modified" 

e.g.
1512480291793 
"1512487510"

**Comment by digitalWestie** [comment]
Bookwhen data doesn't seem to have any 'activity' key --- https://bookwhen.com/api/openactive/event_types :/

**Comment by digitalWestie** [comment]
Goodgym (https://www.goodgym.org/api/happenings) took ages, I think because there are few results per page so it has to page through quite a lot before getting to 2017. Extracted activities fine though.
