### ISSUE TITLE
Display top activities for dataset

### ISSUE THREAD

**Issue by digitalWestie** [openactive/api-dashboard#26]
Use zrevrange e.g. `ZREVRANGE myzset 0 -1` to return top 10 results of the redis activity sets. 

Display this in a bootstrap modal, ajax request template result in order not to perform this query for all the datasets. 

Put a link to this under the 'Summary' column. This is only available to the conforming datasets.

In modal -- have the dataset title e.g. "ActiveNewhal Dataset Summary", then in modal body have show a bootstrap table with top X results.

**Comment by ldodds** [comment]
https://stackoverflow.com/questions/34763090/bootstrap-4-with-remote-modal

**Comment by digitalWestie** [comment]
Should we display the score? Or just ranking?
