### ISSUE TITLE
Display top LA boundaries in dataset summary

### ISSUE THREAD

**Issue by digitalWestie** [openactive/api-dashboard#32]
Restrict to top 10

Display: 
Authority name: No. of opportunities in boundary

Local authority counts are base on data that has geographic coordinates.

Provide link to the original source and attribution for the geojson boundary data.

**Comment by ldodds** [comment]
Attribution of ONS data:

"Contains National Statistics data © Crown copyright and database right [2017]"

**Comment by digitalWestie** [comment]
Make tables side by side. 

Explain that scores aren't necessarily equal to number of opportunities.
