### ISSUE TITLE
Add a column for “Includes geo” to the dashboard

### ISSUE THREAD

**Issue by nickevansuk** [openactive/api-dashboard#33]
### Desired Behaviour
Add a column for “Includes geo” to the dashboard. (i.e. there’s a session containing “geo” with “latitude” and “longitude” of non-null values in the first page somewhere)

### Background
We got this requirement this week, and spoke to two providers who are keen to fix their feed - if we can get this in we can use the status page to help them see why they need to conform.

The reason for this is geocoding is a barrier to data consumption for small / non-commercial data users such, who probably only want to access data in their region from each source and want to filter out the rest (filter available via RDPE https://www.w3.org/2017/08/realtime-paged-data-exchange/#in-stream-filtering)

**Comment by ldodds** [comment]
@digitalWestie as discussed, if we can include this, drawing on the summaries that would be great.

I'd suggest:

* adding new column before "Summary", "Includes co-ordinates"
* value should be tick or cross based on whether there's `geo` data (so you can use the counts you're generating to detect that for now)
* ensure that the data is included in the JSON download

**Comment by digitalWestie** [comment]
I see that one or two of the non-conformant have coordinates e.g. flexidigital, but in different places & with different keys. Maybe for the non-conformant we should put a yellow / gray circle and a question mark instead of saying ':x: No'. 

Otherwise this is done.

**Comment by ldodds** [comment]
We want to reinforce that they should follow the standard model, so its correct that these are a No for the moment.
