### ISSUE TITLE
Add about page with definitions of each column

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#39]
Add a static about page with:

* definitions of each column
* notes on how the summaries are generated

**Comment by ldodds** [comment]
See #42 for some initial suggested text for summaries.

Please also include a note on how often the data is updated.

**Comment by digitalWestie** [comment]
Page added. I'll leave open until you're happy the text offers enough explanation:
 https://api-dashboard-staging.herokuapp.com/about

**Comment by digitalWestie** [comment]
Idea- mention the dashboard github repo in the about page?

**Comment by ldodds** [comment]
Can you make the "Summary" heading say "Dataset Summaries" and make it H2 similar to the "Dashboard columns" heading.

Adding a link to the github repo makes sense. Can you add that at the end under a new h2 heading? "Contribute to this dashboard".

Otherwise text seems fine for now. Happy for you to close after making these two amends
