### ISSUE TITLE
Add timestamp for summaries

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#43]
In the summary table, include a timestamp to indicate when the summary was last updated, e.g. when did we last run the summary job to update the summary information?

This runs daily so its a different time stamp to the table metadata.

**Comment by ldodds** [comment]
Looking at some summaries I'm seeing:

"This summary was last updated: Never"

This should be a timestamp?

**Comment by digitalWestie** [comment]
Appearing on production and staging now. My guess is the `last_updated` wasn't being set until the new summary code was ran early today by the scheduled task.
