### ISSUE TITLE
Add AJAX loading indicator

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#44]
I've noticed on the staging site that there's sometimes a second or so before the summary information appears because its being requested from the server.

Can you add a loading indicator, e.g. a spinner into the body of the modal. Will avoid a user thinking that there's no information.

**Comment by ldodds** [comment]
Might be my connection, but I'm only getting a loading indicator on the staging site now, no content.

Also can you centre align the image?

**Comment by digitalWestie** [comment]
Loading and looks centred here, cache?

**Comment by ldodds** [comment]
Am not seeing the loading indicator now, but am seeing summaries. Closing for now.
