### ISSUE TITLE
Feature: Report metrics to Bothan

### ISSUE THREAD

**Issue by ldodds** [openactive/api-dashboard#46]
We need to collect some metrics on the state of the API ecosystem. The dashboard app is the right place to do that because it already collects some of the basic metrics.

I'm filing this bug as a main feature issue to cover the core requirements, we should decompose this into smaller issues to manage and track progress.

We are using [Bothan](https://bothan.io/) to collect metrics for the Open Active programme. We need the dashboard app to submit some metrics to Bothan on a daily basis.

There's [a production instance of Bothan](https://openactive-metrics.herokuapp.com) for the programme. But we need to [deploy a test instance](https://bothan.io/get-started.html) for development.

To begin with there are three metrics to report. Read the Bothan docs for how to report the metrics.

* `dataset-count` -- the total number of datasets in OpenActive
* `standard-datasets` -- the total number of datasets that implement BOTH of the standards
* `local-authorities-sample` -- the total number of local authorities we've identified in the data feeds in the sampling app. This should be a count of all the unique local authorities (so not just the top ten) that we've found when sampling all of the feeds. Note that we're counting number of local authorities, not how many opportunities we've found in each

There are other metrics to implement later, but this gives us some basic numbers to begin with. 

Tasks (break these out into separate issues):

* [x] Deploy test instance of Bothan in the OA heroku account
* [x] Review Bothan API docs and [Bothan client library](https://github.com/theodi/bothan.rb)
* [x] Implement command-line app to report metrics to Bothan
* [x] Configure app to run daily in the staging and production dashboard apps. 
* [x] The staging app should be configured to use the staging version of Bothan, and the production app the production instance.
* [x] Implement reporting of the `dataset-count` metric
* [x] Implement reporting of the `standard-datasets` metric
* [x] Implement reporting of the `local-authorities-sample` metric

I'll need to provide you with the production credentials for the live Bothan API once we're ready to deploy that part of the application.

**Comment by digitalWestie** [comment]
Prioritise: 
- Implement reporting of the dataset-count metric
- Implement reporting of the standard-datasets metric

**Comment by digitalWestie** [comment]
Use separate scheduled task
